- change-proneness-ranker/pom.xml
- change-proneness-ranker/src/main/java/org/hjug/git/GitLogReader.java
- pom.xml
Hello! It's me again!
As per Issue #7, removed all occurrences of `commons-lang3` dependency coming from `org.apache.commons`.
I saw it was used only at `GitLogReader` for an `isNotBlank()` operation
According to its [documentation](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isNotBlank-java.lang.CharSequence-), it checks for 3 things
1. String is not empty `("")`
2. String is not null
3. String is not just whitespaces alone `("      ")`
To get the same behavior, I replaced the `isNotBlank()` with 
- `Objects.nonNull()` to handle 2
- `!isEmpty()` from `String` class to handle 1
- `trim()` before the `!isEmpty()` check to handle 3
Feel free to let me know if you had something else in mind for #7!
> #7: Remove commons-lang3 dependency

- effort-ranker/src/main/java/org/hjug/metrics/GodClass.java
- effort-ranker/src/test/java/org/hjug/metrics/GodClassParsingTest.java
AbstractRuleViolationFactory is using MessageFormat with the current locale to format. GodClass should do the same thing to parse.
> Parse using locale to match AbstractRuleViolationFactory formatting

- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstJsonReport/RefactorFirstMavenJsonReport.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstMavenCsvReport.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstMavenReport.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/ReportWriter.java
Introduces ability to the Maven plugin to work with projects which lack a root-level POM file. Changes to specific classes are as follows:
RefactorFirstMavenReport
- Set requiresProject parameter to false. A true value will result in MissingProjectException being thrown if no root-level POM file is present. A falsy value is required to enable scanning of projects without a root-level POM file.
- Added check (starting line 133) for default project name & substitution. The MavenProject dependency will use a default project name of "Maven Sub Project (No POM)" if a root-level POM file is not present. If that name is detected, replace it with the name of the project's root directory.
- Added handling (starting line 202) for an upstream bug in MavenProject dependency. This class's getBasedir …
> Add non-root-POM feature to Maven plugin

- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstJsonReport/RefactorFirstMavenJsonReport.java
One line change to set requiresProject parameter of RefactorFirstMavenJsonReport to false. Ensures JSON format behaves correctly with projects not using a root-level POM file.
> RefactorFirstMavenJsonReport config update

- cost-benefit-calculator/src/main/java/org/hjug/cbc/RankedDisharmony.java
- effort-ranker/src/main/java/org/hjug/metrics/GodClass.java
- effort-ranker/src/main/java/org/hjug/metrics/PMDGodClassRuleRunner.java
- effort-ranker/src/test/java/org/hjug/metrics/GodClassParsingTest.java
- effort-ranker/src/test/java/org/hjug/metrics/GodClassRankerTest.java
- graph-data-generator/src/main/java/org/hjug/gdg/GraphDataGenerator.java
- graph-data-generator/src/test/java/org/hjug/gdg/GraphDataGeneratorTest.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstJsonReport/JsonReportDisharmonyEntry.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstMavenCsvReport.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstMavenReport.java
Class name and file name were being conflated. In most cases the two are
the same but not always.
I renamed the existing className property in RankedDisharmony to
fileName to reflect what it actually is.
I added a new className property which is set to the actual
className.
To get class name passed into the logic where RankedDisharmony is
constructed I also had to update the GodClass definition to include
className as well as file name.
The HTML and CVS report output should not change. I updated them to
call getFileName from ranked disharmony rather than getClassName. This
preserves existing behavior.
The only output which should change is the  JSON report which will now expose both fileName and className, letting the
consumer choose which they care about.
> Add true class name

- README.md
- effort-ranker/src/main/java/org/hjug/metrics/GodClassRanker.java
- pom.xml
- refactor-first-maven-plugin/pom.xml
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstMavenReport.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstRealMavenReport.java
Now generating report through mvn site command.  Added GH buttons to mvn site command generated webpage
> #62 mvn site and #70 GH buttons on mvn site generated page

- change-proneness-ranker/pom.xml
- cli/pom.xml
- cost-benefit-calculator/pom.xml
- coverage/pom.xml
- effort-ranker/pom.xml
- graph-data-generator/pom.xml
- pom.xml
- refactor-first-maven-plugin/pom.xml
- report/pom.xml
- test-resources/pom.xml
Github release process didn't seem happy with -M1-SNAPSHOT suffix.
> Update version to 0.5.0.M1-SNAPSHOT

- .github/workflows/maven-pr.yml
- .github/workflows/maven-publish.yml
- .github/workflows/maven.yml
- report/src/main/java/org/hjug/refactorfirst/report/SimpleHtmlReport.java
- Hyperlinking RefactorFirst in report title to RefactorFirst repository so users can learn more about RefactorFirst
- Backed out change to maven.yml since it's not publishing to snapshot when run
> Hyperlinking RefactorFirst in report title

- circular-reference-detector/pom.xml
- circular-reference-detector/src/main/java/org/hjug/app/CircularReferenceDetectorApp.java
- cost-benefit-calculator/src/main/java/org/hjug/cbc/CostBenefitCalculator.java
- report/pom.xml
- report/src/main/java/org/hjug/refactorfirst/report/HtmlReport.java
- report/src/main/java/org/hjug/refactorfirst/report/SimpleHtmlReport.java
Generating Cycle Data tables and rendering cycle images
> Generating Cycle data

- cost-benefit-calculator/src/main/java/org/hjug/cbc/CostBenefitCalculator.java
- Fixed Linux directory repository lookups
- Specified BLEEDING_EDGE as Java version (currenly Java 21) for the Java Symbol Solver
> Fixed issues

- circular-reference-detector/src/main/java/org/hjug/app/CircularReferenceDetectorApp.java
- circular-reference-detector/src/main/java/org/hjug/cycledetector/CircularReferenceChecker.java
- circular-reference-detector/src/main/java/org/hjug/parser/JavaProjectParser.java
- circular-reference-detector/src/test/java/org/hjug/cycledetector/CircularReferenceCheckerTests.java
- circular-reference-detector/src/test/java/org/hjug/parser/JavaProjectParserTests.java
- circular-reference-detector/src/test/resources/javaSrcDirectory/com/ideacrest/parser/testclasses/E.java
- cost-benefit-calculator/src/main/java/org/hjug/cbc/CostBenefitCalculator.java
- cost-benefit-calculator/src/main/java/org/hjug/cbc/RankedCycle.java
- report/src/main/java/org/hjug/refactorfirst/report/SimpleHtmlReport.java
Edge weights represent the number of field declarations of a type + the number of method parameter declarations of a type there are in a class.
> #92 Add weighted edges

- change-proneness-ranker/src/main/java/org/hjug/git/ChangePronenessRanker.java
- change-proneness-ranker/src/main/java/org/hjug/git/GitLogReader.java
- change-proneness-ranker/src/test/java/org/hjug/git/ChangePronenessRankerTest.java
- change-proneness-ranker/src/test/java/org/hjug/git/GitLogReaderTest.java
- cost-benefit-calculator/src/main/java/org/hjug/cbc/CostBenefitCalculator.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstMavenReport.java
- report/src/main/java/org/hjug/refactorfirst/report/CsvReport.java
- report/src/main/java/org/hjug/refactorfirst/report/SimpleHtmlReport.java
- Improved GitLogReader ergonomics
- Optimized git interactions
- Silenced PMD complaints
- Added cycle analysis to Maven report
> Optimize git

- README.md
- change-proneness-ranker/pom.xml
- circular-reference-detector/pom.xml
- cli/pom.xml
- cost-benefit-calculator/pom.xml
- cost-benefit-calculator/src/main/java/org/hjug/cbc/CostBenefitCalculator.java
- coverage/pom.xml
- effort-ranker/pom.xml
- graph-data-generator/pom.xml
- pom.xml
- refactor-first-maven-plugin/pom.xml
- report/pom.xml
- test-resources/pom.xml
- Now handling generated sources gracefully
- Updated README.md
> Handle generated sources

- circular-reference-detector/pom.xml
- circular-reference-detector/src/main/java/org/hjug/app/CircularReferenceDetectorApp.java
- circular-reference-detector/src/main/java/org/hjug/cycledetector/CircularReferenceChecker.java
- circular-reference-detector/src/test/java/org/hjug/cycledetector/CircularReferenceCheckerTests.java
- cost-benefit-calculator/src/main/java/org/hjug/cbc/CostBenefitCalculator.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstMavenReport.java
- report/src/main/java/org/hjug/refactorfirst/report/HtmlReport.java
- report/src/main/java/org/hjug/refactorfirst/report/SimpleHtmlReport.java
- report/src/test/java/org/hjug/refactorfirst/report/HtmlReportTest.java
Replaced generation of png file generation with inline DOT graph generation
> #101 Rendering DOT images instead of png iimages

- cost-benefit-calculator/src/main/java/org/hjug/cbc/CostBenefitCalculator.java
- cost-benefit-calculator/src/main/java/org/hjug/cbc/RankedCycle.java
- report/src/main/java/org/hjug/refactorfirst/report/HtmlReport.java
- report/src/main/java/org/hjug/refactorfirst/report/SimpleHtmlReport.java
Only calculating cycle class churn when `showDetails = true`
> #93 Only calculating cycle class churn when `showDetails = true`

- change-proneness-ranker/pom.xml
- circular-reference-detector/pom.xml
- circular-reference-detector/src/main/java/org/hjug/parser/JavaProjectParser.java
- cli/pom.xml
- cost-benefit-calculator/pom.xml
- coverage/pom.xml
- effort-ranker/pom.xml
- graph-data-generator/pom.xml
- pom.xml
- refactor-first-maven-plugin/pom.xml
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstMavenReport.java
- report/pom.xml
- report/src/main/java/org/hjug/refactorfirst/report/HtmlReport.java
- report/src/main/java/org/hjug/refactorfirst/report/SimpleHtmlReport.java
- test-resources/pom.xml
- Rendering DOT files in Maven report
- Logging classes being parsed for circular reference chcecker
> Render dot graphs in maven report

- README.md
- report/pom.xml
- Removed dependencies jgrapht-ext:1.3.0 and jgrapht-core:1.3.0 in the report module.  They were unneeded and jgrapht-ext creates a transitive dependency on org.tinyjee.jgraphx:jgraphx:3.4.1.3, which has a 9.8 CVE score - see CVE-2017-18197
- Updated README.md to refer to version 0.6.1 ahead of release
> Remove jgrapht-core and jgapht-ext from report module

- codebase-graph-builder/src/test/java/org/hjug/graphbuilder/visitor/JavaNewClassVisitorFullTest.java
- codebase-graph-builder/src/test/java/org/hjug/graphbuilder/visitor/testclasses/newClass/A.java
- refactor-first-maven-plugin/src/main/java/org/hjug/mavenreport/RefactorFirstMavenReport.java
- report/src/main/java/org/hjug/refactorfirst/report/HtmlReport.java
- report/src/main/java/org/hjug/refactorfirst/report/SimpleHtmlReport.java
- report/src/test/java/org/hjug/refactorfirst/report/HtmlReportTest.java
- Using js delivr instead of unpkg to prevent graph rendering issues
- Added auto margin around the rendered DOT graph to improve ease of page navigation 
- Added unit tests to confirm that class counts are correct for the Java codebase analyzer
> #139 use js delivr instead of unpkg

- change-proneness-ranker/src/main/java/org/hjug/git/GitLogReader.java
Simply deleted two unused functions
> Reduce JGit memory use #82

- dsm/src/main/java/org/hjug/dsm/DSM.java
- dsm/src/main/java/org/hjug/dsm/EdgeToRemoveInfo.java
- dsm/src/main/java/org/hjug/dsm/OptimalBackEdgeRemover.java
- dsm/src/main/java/org/hjug/dsm/SparseGraphCircularReferenceChecker.java
- dsm/src/main/java/org/hjug/dsm/SparseIntDWGEdgeRemovalCalculator.java
- dsm/src/test/java/org/hjug/dsm/DSMTest.java
- dsm/src/test/java/org/hjug/dsm/OptimalBackEdgeRemoverTest.java
- pom.xml
- report/src/main/java/org/hjug/refactorfirst/report/SimpleHtmlReport.java
Attempted to perform cycle back edge removal analysis, but will remove later after Minimum Feedback Arc & Vertex Set algorithms are implemented.  Keeping for now to capture how to use the SparseIntDirectedWeightedGraph class.
> Improve analysis performance
